name: Generate F-Droid repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Install F-Droid server software
        run: |
         sudo add-apt-repository ppa:fdroid/fdroidserver
         sudo apt-get update
         sudo apt-get install fdroidserver

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml

      - uses: actions/setup-go@v2
        name: Set up Go
        with:
          go-version: '^1.17.0' 

      - name: Download new apps & update existing ones
        run: go run main.go -ap=../apps.yaml -rd=../fdroid/repo -pat="${{ secrets.GH_ACCESS_TOKEN }}"
        working-directory: metascoop

      - name: Commit all changes
        run: | 
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git add fdroid
          git commit -m"Automated update" || true
          git push
