name: Generate F-Droid repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Install F-Droid server software
        run: |
         sudo add-apt-repository ppa:fdroid/fdroidserver
         sudo apt-get update
         sudo apt-get install fdroidserver

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml
