name: Generate F-Droid repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

permissions:
  contents: write

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: windows-latest #ubuntu-latest

    env:
      PROJECT_LOCATION: C:\fdroid # ${{ github.workspace }}
      FDROID_REPO_BRANCH: fdroid-repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout F-Droid repository branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.FDROID_REPO_BRANCH }}
          path: fdroid-2

      - run: mv fdroid-2/repo fdroid/repo || true

      - name: Create basic directory structure (Linux/macOS)
        if: runner.os != 'Windows'
        run: mkdir -p fdroid/repo

      - name: Create basic directory structure (Windows)
        if: runner.os == 'Windows'
        # https://docs.python.org/3/library/venv.html
        run: |
          pip install androguard
        #  pip install git+https://github.com/uwx/fdroidserver.git
        #  mkdir fdroid\repo -ErrorAction SilentlyContinue

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ github.token }}

      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install tsx globally
        run: pnpm add -g tsx

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Restore correct mtime (Windows)
        if: runner.os == 'Windows'
        run: curl https://raw.githubusercontent.com/MestreLion/git-tools/main/git-restore-mtime | python -

      - name: Restore correct mtime (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt install git-restore-mtime
          git restore-mtime --force

      - name: Install F-Droid server software (Windows)
        if: runner.os == 'Windows'
        run: pip install git+https://github.com/uwx/fdroidserver.git

      - name: Install F-Droid server software (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo add-apt-repository ppa:fdroid/fdroidserver
          sudo apt-get update
          sudo apt-get install fdroidserver

      - uses: actions/setup-go@v5
        name: Set up Go
        with:
          go-version: '^1.17.0'

      - name: Copy fdroid stuff to C drive
        if: runner.os == 'Windows'
        shell: pwsh
        run: Copy-Item -Path . -Destination $env:PROJECT_LOCATION -Recurse

      - name: Install modules for project
        run: pnpm install
        working-directory: ${{ env.PROJECT_LOCATION }}

      - name: Add templated secrets to config.yml
        run: |
          pnpm install
          tsx deyaml.ts
        working-directory: ${{ env.PROJECT_LOCATION }}/jshelpers
        env:
          keystorepass: ${{ secrets.keystorepass }}
          keypass: ${{ secrets.keypass }}
          repo_keyalias: ${{ secrets.repo_keyalias }}
          keydname: ${{ secrets.keydname }}
          repo_url: https://raw.githubusercontent.com/${{ github.repository }}/${{ env.FDROID_REPO_BRANCH }}/repo
          virustotal_apikey: ${{ secrets.virustotal_apikey }}

      - name: Install modules for metascoop-ts
        run: pnpm install
        working-directory: ${{ env.PROJECT_LOCATION }}/metascoop-ts

      - name: Run metascoop-ts
        run: tsx ${{ env.PROJECT_LOCATION }}/metascoop-ts/src/index.ts
        working-directory: ${{ env.PROJECT_LOCATION }}/metascoop-ts
        env:
          GH_ACCESS_TOKEN: ${{ github.token }}

      #- name: Run update script
      #  id: run-update-script
      #  run: bash update.sh 2>&1
      #  working-directory: ${{ env.PROJECT_LOCATION }}
      #  env:
      #    GH_ACCESS_TOKEN: ${{ github.token }}

      - name: Compress Images
        #if: runner.os != 'Windows' # TODO: container actions don't work on Windows
        id: calibre
        uses: uwx/actions/calibre-image-actions@main
        with:
          githubToken: ${{ github.token }}
          compressOnly: true
          commitName: github-actions
          commitEmail: github-actions[bot]@users.noreply.github.com
          location: ${{ env.PROJECT_LOCATION }}

      - name: Deploy
        # if: steps.run-update-script.outputs.exitcode == '0'
        uses: uwx/actions/git-publish-subdir@main
        env:
          REPO: self
          BRANCH: ${{ env.FDROID_REPO_BRANCH }}
          FOLDER: ${{ env.PROJECT_LOCATION }}/fdroid/repo
          TARGET_DIR: repo
          GITHUB_TOKEN: ${{ github.token }}
          SQUASH_HISTORY: true
          COMMIT_NAME: github-actions
          COMMIT_EMAIL: github-actions[bot]@users.noreply.github.com
          TEMP_DIR: C:\_temp # ${{ runner.temp }}

      - name: Copy updated README to main repo
        if: runner.os == 'Windows'
        shell: pwsh
        run: Copy-Item -Path "$env:PROJECT_LOCATION\README.md" -Destination "${{ github.workspace }}\README.md" -Recurse -Force

      - name: Write APK count to file for shields.io
        shell: pwsh
        run: |
          (Get-ChildItem -Filter *.apk -Path "$env:PROJECT_LOCATION\fdroid\repo" -File -Recurse | Measure-Object).Count | Out-File "${{ github.workspace }}\.github\apk-count.json"

      - name: Push updated readme and apk-count.json if needed
        shell: pwsh
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config pull.rebase true

          git add README.md .github\apk-count.json
          git commit -m "Automated update README and APK count"
          git add fdroid/metadata
          git commit -m "Automated update cached repo metadata"
          git pull
          git push

          exit 0
