name: Generate F-Droid repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

permissions:
  contents: write

jobs:
  apps:
    name: "Generate repo from apps listing"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: fdroid-repo
          path: fdroid/repo

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Restore correct mtime
        run: |
          sudo apt install git-restore-mtime
          git restore-mtime

      - name: Install F-Droid server software
        run: |
         sudo add-apt-repository ppa:fdroid/fdroidserver
         sudo apt-get update
         sudo apt-get install fdroidserver

      #- name: Set up repo secrets
      #  run: |
      #    echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
      #    echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml

      - uses: actions/setup-go@v2
        name: Set up Go
        with:
          go-version: '^1.17.0'

      - run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Run update script
        id: run-update-script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ github.token }}
          keystorepass: ${{ secrets.keystorepass }}
          keypass: ${{ secrets.keypass }}
          repo_keyalias: ${{ secrets.repo_keyalias }}
          keydname: ${{ secrets.keydname }}
          repo_url: https://raw.githubusercontent.com/${{ github.event.repository.name }}/fdroid-repo
          virustotal_apikey: ${{ secrets.virustotal_apikey }}

      - name: Deploy
        if: steps.run-update-script.outputs.exitcode == '0'
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: fdroid-repo
          FOLDER: fdroid/repo
          GITHUB_TOKEN: ${{ github.token }}
